version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./backup:/var/opt/mssql/backup
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr & 
        sleep 30 && 
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'RESTORE DATABASE AdventureWorks FROM DISK = N''/var/opt/mssql/backup/AdventureWorks2022.bak'' WITH MOVE ''AdventureWorks_Data'' TO ''/var/opt/mssql/data/AdventureWorks.mdf'', MOVE ''AdventureWorks_Log'' TO ''/var/opt/mssql/data/AdventureWorks_log.ldf'', REPLACE'
      "